### ISSUE TITLE
README encoding in setup.py on Python 3

### ISSUE THREAD

**Issue by nvictus** [mdshw5/pyfaidx#100]
I recently deployed an application that failed to install a package with pyfaidx as a dependency using pip in a Python 3.5 environment. It looks like it's choking on some non-ascii characters in README.rst, because I'm guessing the default encoding on that machine is ascii.

```
Collecting pyfaidx
  Using cached pyfaidx-0.4.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7gn60v09/pyfaidx/setup.py", line 26, in <module>
        long_description=open('README.rst').read(),
      File "/home/main/anaconda2/envs/binder/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16689: ordinal not in range(128) 
```
Asking pip for `pyfaidx<0.4.7.1` ending up working. Anyways, I suspect specifying 'utf-8' should fix the problem.

**Comment by mdshw5** [comment]
Merged in #101. Thanks for the work!
