### ISSUE TITLE
Check for malformed .fai entries

### ISSUE THREAD

**Issue by mdshw5** [mdshw5/pyfaidx#102]
.fai index files are created by several tools, including this one, and so are suspect for data integrity. There might be a few cases to check for and warn the user if encountered:
- [ ] etal/cnvkit#136 exposes a negative [`bstart`](https://github.com/mdshw5/pyfaidx/blob/5570ccb0b3303b62742a2ffa07b14de52c04e4df/pyfaidx/__init__.py#L479) value. The python IOError is not very informative, so we should probably catch that error and reraise with some context (a line from the index file for example)
- [ ] If the .fai is generated, and then the .fa is modified this would usually trigger #50, but if not we should maybe check for the '>' at the beginning of each defline.
- [ ] maybe other cases...?

**Comment by etal** [comment]
Related to the second case, timestamps can be misleading if the .fa and .fai files were copied over a network, or generally without retaining the original modification time on each file. For example, if a download is interrupted, the .fai could be complete but the corresponding .fa file could be truncated. Think it's feasible for pyfaidx to do a quick sanity check if the timestamps or .fai contents are suspicious?
