### ISSUE TITLE
Retrieving sequences loses part of the defline

### ISSUE THREAD

**Issue by deannachurch** [mdshw5/pyfaidx#103]
Hi Matt,
I have a fasta file with deflines that look like:
>19364 edges=1463157..1970894 left=2489499 right=2476073 ver=1.7 style=4

When I use faidx to index this file and then retrieve the sequence, the new defline just looks like:
>19364

It would be better to retrieve the entire defline, not just the seqid. Is this possible?

best, 
-deanna

**Comment by mdshw5** [comment]
This should be possible since v0.3.7, but I didn't make it too obvious. From the Readme:

Sequence names are truncated on any whitespace. This is a limitation of the indexing strategy. However, full names can be recovered:
```
# new in v0.3.7
>>> from pyfaidx import Fasta
>>> genes = Fasta('tests/data/genes.fasta')
>>> for record in genes:
...   print(record.name)
...   print(record.long_name)
...
gi|563317589|dbj|AB821309.1|
gi|563317589|dbj|AB821309.1| Homo sapiens FGFR2-AHCYL1 mRNA for FGFR2-AHCYL1 fusion kinase protein, complete cds
gi|557361099|gb|KF435150.1|
gi|557361099|gb|KF435150.1| Homo sapiens MDM4 protein variant Y (MDM4) mRNA, complete cds, alternatively spliced
gi|557361097|gb|KF435149.1|
gi|557361097|gb|KF435149.1| Homo sapiens MDM4 protein variant G (MDM4) mRNA, complete cds
...
```

**Comment by mdshw5** [comment]
Please let me know if this doesn't work properly and I'll look into a fix. The whitespace truncation is for compatibility with existing indexing tools, but I agree there's no reason not to retrieve the full name during runtime.

**Comment by deannachurch** [comment]
I should have been clearer that I was using the command line tool:

```
faidx assembly_pseudohap2.1.fasta '19364' >hap1_19364.fa
```

Is this functionality available there too? Not obvious from the docs.

**Comment by mdshw5** [comment]
It should be the `--full-names | -f` option. I'm not sure what version I added that too, but it should be in the most recent cli script.

**Comment by deannachurch** [comment]
yes! thanks.

**Comment by mdshw5** [comment]
You're welcome - nice to hear from you again 😊
