### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16813: ordinal not in range(128)

### ISSUE THREAD

**Issue by liufengxia99** [mdshw5/pyfaidx#105]
hi
 python2.7
ubuntu 14.04.4

python setup.py install
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    long_description=open('README.rst').read(),
  File "/home/gene-rd-lfx/anaconda2/lib/python2.7/encodings/ascii.py", line 17, in decode
    return codecs.ascii_decode(input,self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16813: ordinal not in range(128)

i download the source at 2016-10-18, and the installing doesn't go on, please.
there is a similar question and fixed while i still can't fix my problem( https://github.com/erocarrera/pefile/issues/105#userconsent# )

**Comment by mdshw5** [comment]
It looks like this was related to a previous issue, but was never fixed. Thanks for bringing it to my attention! I'll push a bug fix release as [v0.4.8.1](https://github.com/mdshw5/pyfaidx/releases/tag/v0.4.8) (link will work when I push the release to PyPI.

**Comment by mdshw5** [comment]
@liufengxia99 would you please confirm that the current PyPI version fixed this issue for you?
