### ISSUE TITLE
pyfaidx does not successfully install on Travis

### ISSUE THREAD

**Issue by mccalluc** [mdshw5/pyfaidx#106]
I am trying to test on Travis a bash script that uses faidx. I [install pyfaidx](https://github.com/refinery-platform/get-reference-genomes/pull/5/files#diff-63ab6decfd52638355f6a527c3c6dee2R18) using pip, and [`faidx --version` works](https://travis-ci.org/refinery-platform/get-reference-genomes/builds/180523163#L171), but when I try to actually index a file, [it fails](https://travis-ci.org/refinery-platform/get-reference-genomes/builds/180523163#L332): 
```
$ faidx hg19.fa
Traceback (most recent call last):
  File "/home/travis/.local/bin/faidx", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3018, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 612, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 918, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 805, in resolve
pkg_resources.DistributionNotFound: pyfaidx==0.4.8.1
```

My best guess right now is that it is being installed under a different python environment than it ends up being called from, but I don't think I'm doing anything odd.

My next step will be to make a new branch from scratch with a minimal reproducer.

**Comment by mccalluc** [comment]
(I have not been able to create a minimal reproducer, so I think there's something else I'm doing in the main script which is causing the problem.)

**Comment by mdshw5** [comment]
I'll take a look and see if I can find any issues :)

**Comment by mdshw5** [comment]
It's worth noting that you can run the `faidx` script as a module like: `python -m pyfaidx.cli`

**Comment by mccalluc** [comment]
Let me try that: It's something about the environment that I run it in: There's a point where it works, and a point where it doesn't, so I'm doing effectively a binary search to figure out what makes the difference: I'll let you know when I've figured it out. Thanks!

**Comment by mdshw5** [comment]
I think setting `language: ruby` actually changes the environment when you're running your tests. The system python on Travis is `/usr/bin/python`, so you might try targeting that. You can take a look at my [`before_script` section](https://travis-ci.org/mdshw5/pyfaidx/jobs/170118902/config) for a case where I'm using the system python version and not the `language: python` version.

**Comment by mccalluc** [comment]
Found it: For some reason, I was setting
```
HOME=`pwd`
```
If I remove that, faidx works. I need to go through the history to understand why that was added. I'll close this: I don't really understand why it makes a difference, but it has nothing to do with this repo.

**Comment by mdshw5** [comment]
Interesting. Glad you figured it out!
