### ISSUE TITLE
question about installation

### ISSUE THREAD

**Issue by Vivianstats** [mdshw5/pyfaidx#107]
Hello,

I have installed faidx using `pip install --user  pyfaidx` and got the following results:

Downloading/unpacking pyfaidx
  Downloading pyfaidx-0.4.8.1.tar.gz
  Running setup.py (path:/tmp/pip_build_liwei92/pyfaidx/setup.py) egg_info for package pyfaidx
    
    warning: no files found matching 'docs/build/html/*'
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from pyfaidx)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.7 in /usr/local/lib/python2.7/dist-packages (from pyfaidx)
Installing collected packages: pyfaidx
  Running setup.py install for pyfaidx
    
    warning: no files found matching 'docs/build/html/*'
    Installing faidx script to /home/liwei92/.local/bin
  Could not find .egg-info directory in install record for pyfaidx
Successfully installed pyfaidx
Cleaning up...

But when I tried to use it in command  lines with `faidx --split-files  example.fa`, it says

faidx: command not found

Am I missing something? I appreciate it if anyone can help.

**Comment by mdshw5** [comment]
No worries. You should add `/home/liwei92/.local/bin` to your `$PATH` environment variable:
```bash
PATH=$PATH:/home/liwei92/.local/bin
```
You can add that line to your `~/.bashrc` file so the change is persistent between logins. You can find more information here: http://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path

The TLDR is that `$PATH` is where your shell looks for programs it can execute, so when you type `faidx`, bash will find `/home/liwei92/.local/bin/faidx`.
