### ISSUE TITLE
Use env in the before_script in .travis.yml

### ISSUE THREAD

**Issue by terrycojones** [mdshw5/pyfaidx#112]
It would be good to change these lines:

```
before_script:
    - /usr/local/bin/pip install --user biopython
    - /usr/bin/python tests/data/download_gene_fasta.py
```

to use `env` so that the user's current (virtual environment) `python` and `pip` are used:

```
before_script:
    - /usr/bin/env pip install --user biopython
    - /usr/bin/env python tests/data/download_gene_fasta.py
```

**Comment by mdshw5** [comment]
I honestly can't remember why, but I was trying to install Biopython using the system python2.7 on Travis, since Biopython doesn't support python3.2. I'll go ahead and make the change and see if anything breaks...
