### ISSUE TITLE
Enhancement: Support numpy.int32 and numpy.int64

### ISSUE THREAD

**Issue by dburkhardt** [mdshw5/pyfaidx#114]
Currently, line 502 and 503 of __init__.py requires all ints passed to faidx.fetch() to belong to the `integer_types` classes as determined by `six`.
 
```python
def from_file(self, rname, start, end, internals=False):

...

    assert isinstance(start, integer_types)
    assert isinstance(end, integer_types)
```

This is frustrating because I routinely use pandas.dataframes to work with large sets of genomic coordinates and the default numeric int is a numpy.int64. numpy.int64 is not of type `int` but should still be compatible with the pyfaidx fetch operation. It's ugly to need to cast all my numpy.int64 to ints when I do a fetch. `fasta['chr1'][int(start)][int(end)]`

Solution: if `assert isinstance` fails, test for equality if `start` and `end` are cast to int. I think this is the only relevant quality of an `int` for this case, and you don't need to import numpy for it to work.

```python
try:
    assert isinstance(start, integer_types)
    assert isinstance(end, integer_types)
except AssertionError:
    assert assertEqual(start, int(start))
    assert assertEqual(end, int(end))
```

I've tested a few cases and this works for me.

Really, I'm not sure that the first set of assertions is needed, but this would be a minimal change to function that would add support for numpy.int32 and numpy.int64 without needed to directly import numpy.

**Comment by mdshw5** [comment]
Thanks for reaching out about your use case. I actually like the idea of testing equality with the interpreter's concept of an integer, and will just replace the current assertions. I'll be pushing a new release soon with features implemented in #77, so I'll bundle this change in v0.4.9.
