### ISSUE TITLE
It would be good to have an 0.4.8.5 release

### ISSUE THREAD

**Issue by terrycojones** [mdshw5/pyfaidx#115]
The latest changes re reading bgzf compressed files are not yet on PyPI.

**Comment by mdshw5** [comment]
Sure, that's understood. I'll cut a release, but I think we need to raise a warning that BGZF support is still experimental. See my last comment in #77. I think it's really close, but there's a problem when a fetch spans multiple blocks...

**Comment by mdshw5** [comment]
I've just tagged the release, but need to allow tests to fail before it will be released.

**Comment by terrycojones** [comment]
Just commented on #77.
