### ISSUE TITLE
xargs faidx - copies all input fasta file

### ISSUE THREAD

**Issue by TreeT2** [mdshw5/pyfaidx#119]
Hi All,
I am using pyfaidx to extract fasta sequence from a multifasta file using a list of locus tags.
I have two lists of tags and one list work perfect but when I execute the second it would appear its just copying all the information from the input fasta. Really weird. Ive already looked over all my data to ensure its valid so I cannot see where the issue is at present.

examples: 
List.txt 
JFCCLHHB_00692
CKEMPBAI_00693
FBNBCCDE_01742
OMPPMJLG_02124
GKEHKBJF_02074

files.fasta
>NOLHFCLD_00001 Magnesium-transporting ATPase, P-type 1
atgc
>NOLHFCLD_00003 Serine transporter
atgc

my command is as follows
```
for f in *.fna; do 
f=$(basename $f .fna); xargs faidx $f.fna < tags.txt > $PWD/out/$f.fas; done
```

**Comment by mdshw5** [comment]
Thanks for reaching out. Does your list contain any blank lines? The default action for `faidx` when no regions are passed is to produce the entire file.

**Comment by TreeT2** [comment]
Thanks mdshw5. I removed any whitespaces using  `sed '/^\s*$/d'`
and tried again and its working fine :)
