### ISSUE TITLE
keep fasta header lines unmodified, if ranges are provided

### ISSUE THREAD

**Issue by tolot27** [mdshw5/pyfaidx#121]
Currently, the range coordinates are appended to the sequence ID, if specified (i. e. `contig1:20-200`). I want to keep the FASTA header lines unmodified. I tried to fix it by myself but there are some mixtures of long_name and full_name in the source code.

**Comment by tolot27** [comment]
What me confuses is that the command line parameter `--full-names` is passed as argument `long_names`.  I suggest renaming full-names/long_names to full-header, at least in the source code. That would make it easier to add new parameters addressing this issue.

**Comment by mdshw5** [comment]
Yeah, the `.long_name` property for a `Sequence` object just constructs the `seq:start-end (complement)`  string, while the `FastaRecord.long_name` property retrieves the entire defline (header) from the fasta file. These are really two distinct actions, and it's unfortunate I've named them identically. 

I previously deprecated `Sequence.longname` in favor of `Sequence.long_name`, so I'll move `Sequence.long_name -> Sequence.fancy_name` since that's what I initially wanted to call it anyway.

**Comment by mdshw5** [comment]
Is this the behavior you were expecting?

With coordinates:
```shell
$ faidx --auto-strand tests/data/genes.fasta 'gi|563317589|dbj|AB821309.1|:100-1'
>gi|563317589|dbj|AB821309.1|:100-1 (complement)
CTAATGTGGTATCCTCAACTAAACTGAAGGAGGGCCGGGCCAGGGACAAGGTTGCCATGGTGACCACGAC
CAGGCAGATGAAACGACCCCAGCTGACCAT
```

Without coordinates:
```shell
$ faidx --no-coords --auto-strand tests/data/genes.fasta 'gi|563317589|dbj|AB821309.1|:100-1'
>gi|563317589|dbj|AB821309.1|
CTAATGTGGTATCCTCAACTAAACTGAAGGAGGGCCGGGCCAGGGACAAGGTTGCCATGGTGACCACGAC
CAGGCAGATGAAACGACCCCAGCTGACCAT
```

**Comment by tolot27** [comment]
I'm unsure ich that's wächst Ihr expect. I just want an option which does not modify the ID or better, not changing the ID should be the default behavior as it was with some previous versions. 
It looks like your second example with the `--no-coords` parameter removes an already present

**Comment by tolot27** [comment]
Okay, your commit does not remove already existing coordinates.
Regarding to my second concern of appending additional coordinates: this supports my suggestion that no-coords should be the default. Otherwise it would become a bit confusing if someone extracts nested ranges.

**Comment by mdshw5** [comment]
I think I’m going to leave the defaults as is. To me it’s quite a bit more confusing to extract a subsequence and have it labeled exactly the same as the original subject sequence. You’re never going to please everyone! Thanks for your contribution!

**Comment by tolot27** [comment]
Thanks for the really fast implementation and also for merging my PR.
