### ISSUE TITLE
Tiny typo: diffent -> different

### ISSUE THREAD

**Issue by croth1** [mdshw5/pyfaidx#132]
https://github.com/mdshw5/pyfaidx/blob/7b4d8d7aceadaa1fde05846e854e6eccdba38b77/pyfaidx/__init__.py#L121

The error is a bit cryptic as well - had to check the  code to understand what's going on :slightly_smiling_face:

**Comment by mdshw5** [comment]
Thanks! I'll merge and think about how to better phrase this error message.

**Comment by mdshw5** [comment]
Oh :) thought this was a pull request.
