### ISSUE TITLE
Make pyfaidx available on py3.7

### ISSUE THREAD

**Issue by VidJa** [mdshw5/pyfaidx#149]
Is it possible to make pyfaidx available in the pypi channel for python 3.7.x?

**Comment by mdshw5** [comment]
Could you provide some more information about this? The package is installable from pypi and passes tests under 3.7. Are you referring to the trove classifiers? Those should probably be updated.

**Comment by VidJa** [comment]
you are right.. I was confused by the lack of 3.7 in the classifiers. It turned out I couldn't install due to an issue on our side.
