### ISSUE TITLE
--split-files

### ISSUE THREAD

**Issue by nservant** [mdshw5/pyfaidx#154]
Hi,
The --split-files option seems to change the sequence name in some cases ...
here is a simple example :

```
>>more test.fa 
>HPV16_144-1
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
>HPV55-12
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```

```
>>faidx --split-files test.fa
>>>>ls
HPV16_1441.fa  HPV5512.fa  test.fa  test.fa.fai
```

Is there a way to keep the original names ?
Thanks

**Comment by mdshw5** [comment]
Thanks for raising this issue. Indeed I was a bit too strict with filename sanitation:
https://github.com/mdshw5/pyfaidx/blob/843f69c1acbee3838081d7200438bbe49a95a88e/pyfaidx/cli.py#L9

https://github.com/mdshw5/pyfaidx/blob/843f69c1acbee3838081d7200438bbe49a95a88e/pyfaidx/cli.py#L38-L39

I'll replace the existing logic with something more robust, such as [this](https://github.com/django/django/blob/efc3e32d6d7fb9bb41be73b80c8607b653c1fbd6/django/utils/text.py#L222-L232), from the Django project.

**Comment by mdshw5** [comment]
@nservant If you care to test these changes you can install the current master branch using `pip install -e git+https://github.com/mdshw5/pyfaidx.git#egg=pyfaidx`.
