### ISSUE TITLE
How to specify how the consensus sequence should be built?

### ISSUE THREAD

**Issue by larahurban** [mdshw5/pyfaidx#171]
Hi, 

I am sorry for asking a quite simple question, but I can unfortunately not find any documentation about this, and I am also not sure if I am reading the raw code of the function correctly: 

I am using FastaVariant to create a consensus sequence per sample; all exemplary code uses the default parameter of "het/hom = True", but I was wondering what they mean? Also, what happens in the case of a missing genotype call, and is there a way to specify that the alternative allele should be preferred in the case of a heterozygous variant (I am investigating a dominant phenotype)? 

Thank you very much!

Best wishes,
Lara

**Comment by mdshw5** [comment]
Hi @larahurban. I've just come back from vacation so please excuse the delay in answering. I really never did document the `FastaVariant` class very well, but here's the way it works:
- Only SNVs are supported, so MNVs and indels are ignored.
- Only called sites are used, so any position that does not have a called genotype in the sample of interest will be using the reference allele.
- The `het` and `hom` parameters determine whether to use the alternate allele (`true`) for each type genotype call. 
- There is also a `call_filter` parameter that accepts expressions that evaluate against the FORMAT fields. The example I include in the README excludes homozygous sites using `call_filter`, but you could use it to exclude calls based on GQ or DP.

**Comment by larahurban** [comment]
Thank you very much, Matt!
