### ISSUE TITLE
Incomplete index 

### ISSUE THREAD

**Issue by marco-mariotti** [mdshw5/pyfaidx#174]
Hi,
I noticed that upon calling Fasta(filename), pyfaidx starts building the index directly in filename+'.fai'.
The problem is that if the process is stopped before finishing for whatever reason, the resulting file will be recognized as a valid file even if basically empty (e.g. try with Ctrl-C). Since the path to the index file is hardcoded, it is hard to circumvent this. 
I recommend building the index to a temporary file ('.fai.tmp', for example) and move it to its final location only after the index is correctly built.

Thanks,

**Comment by mdshw5** [comment]
That's a very good idea @marco-mariotti. Have you encountered such incomplete index files before?

**Comment by mdshw5** [comment]
@marco-mariotti I implemented your suggestion and released v0.6.0 to PyPI. Thanks again.

**Comment by marco-mariotti** [comment]
Terrific, thanks! And thanks for developing this awesome package.
