### ISSUE TITLE
fool proof faidx .bed file documentation

### ISSUE THREAD

**Issue by darked89** [mdshw5/pyfaidx#177]
Hello,

Since probably I was neither the first nor the last bitten by the 1-based faidx command line coordinates and a say region.bed 0-based ones it may make sense to add:

```
-b BED, --bed BED     bed file of regions (zero based)
```

Hope it helps,

DK

**Comment by mdshw5** [comment]
Thanks for the suggestion. Indeed 0-based vs 1-based start coordinates will be confusing Bioinformaticians for decades to come. I’ll post the [coordinate description](https://en.wikipedia.org/wiki/BED_(file_format)#Coordinate_system) here for posterity and release a new version with this change.
