### ISSUE TITLE
Migration to pyproject.toml?

### ISSUE THREAD

**Issue by palao** [mdshw5/pyfaidx#186]
Hi, again.
The current best practices in the python community is to use a static source of metadata for a project in a `pyproject.toml` file instead of using `setup.py` (even in combination with `setup.cfg`), see [PEP 621](https://www.python.org/dev/peps/pep-0621).
Is this something to be considered for this project? If yes, I offer a hand: I can make a PR...

PS notice that it has no impact on the end users that `pip install` the project. It's mostly relevant for developers. But I think it is a good thing to have.

**Comment by mdshw5** [comment]
This looks like a good idea (thanks for sharing the PEP). I’d love some help on this as I’ve not used this system before.

**Comment by palao** [comment]
Great. I'll propose a PR asap.

**Comment by palao** [comment]
Question: how do you tag a release? Do you use bum2version, or something similar? Or do you just add a tag to the repo?

**Comment by mdshw5** [comment]
Thanks for sharing this tool. I do currently tag releases, and use semantic versioning to build version numbers for test packages. The CI releases package builds to test-pypi and pypi using these versions, and stable builds are only pushed on new tags. I do like the current system, but could be convinced to change. However, I don't quite see why a different system is necessary, as development happens under VCS, and released versions contain explicit semantic version strings already.

**Comment by mdshw5** [comment]
Hey @palao. I still need to take some time to digest this so thanks for your patience!

**Comment by marcelm** [comment]
> From [PEP 621](https://www.python.org/dev/peps/pep-0621/), it is clearly advisable to use a static version number in the project.

It is totally fine to use dynamic version numbers, you just need to remember to write `dynamic = ["version"]` in the `pyproject.toml`. [setuptools-scm](https://pypi.org/project/setuptools-scm/), which pyfaidx uses, has a large user base and when PEP 621 was written, this use case was taken into account.

(You may have misread PEP 621: The section *above* the version number describes the package *name*, which indeed must be statically defined.)

To be honest, as much as I look forward to defining metadata in a standardized way in `pyproject.toml`, PEP 621 support in setuptools is still marked as *experimental*. I would wait one or two setuptools releases until migrating.
