### ISSUE TITLE
Assess whether Fasta class is actually pygr API compatible

### ISSUE THREAD

**Issue by mdshw5** [mdshw5/pyfaidx#21]
I wrote the Fasta class to provide some pygr interface elements, and then mention that pyfaidx has a pygr-compatible interface. I'm not sure this is true, and should evaluate whether implementing more of the pygr interface would be worthwhile.

**Comment by mdshw5** [comment]
Judging by the pygr [mailing list](https://groups.google.com/forum/#!forum/pygr-dev) it seems like the module is unsupported, and the annotation database ("worldbase") is offline now. All links to the UCLA servers are broken, and I can't access the manuscript. @ctb what happened to the pygr project?

**Comment by mdshw5** [comment]
The `pygr.seqdb.SequenceFileDB` class is the API I will target for full compatibility. Other parts of `pygr` seem out of scope for `pyfaidx`.

**Comment by mdshw5** [comment]
The section on [indexing](https://github.com/cjlee112/pygr/blob/master/doc/rest/sequences.rst#sequence-indexing) has attributes I'll implement:

- [ ] `Sequence.orientation`

Several `pygr` classes map more or less directly to `pyfaidx` classes:
```
pygr.seqdb.SequenceFileDB == pyfaidx.Fasta
pygr.classutil.FileDBSequence == pyfaidx.FastaRecord
pygr.sequence.SeqDBSlice == pyfaidx.Sequence
```

Aspects of the `pygr` API I will not be implementing:

- non-pythonic slicing:
```python
>>> str( chr01[0:10])
'CCACACCACA'
>>> str( chr01[10:0]  )
'TGTGGTGTGG'
```
The alternative strategy is to always use the explicit reverse complement:
```python
>>> str( -chr01[0:10])
'TGTGGTGTGG'
```

**Comment by huguesfontenelle** [comment]
I replaced `pygr` with `pyfaidx` in my code, and my test units pass fine.
They aren't specifically designed to test the retrieval of fasta sequences, but something would have gone wrong if `pyfaidx`wasn't compatible with `pygr`, I believe.
Note that I'm handling reverse complements and negative stands myself (I was not relying on `pygr` for that), so I can't say if that part works fine.
