### ISSUE TITLE
Missing library packaging 

### ISSUE THREAD

**Issue by nerilbl** [mdshw5/pyfaidx#220]
I got the biopython needs to be >= 1.73 error even when having 1.83. for fasta.bgz files.
Debugging it leav me to the [version test ](https://github.com/mdshw5/pyfaidx/blame/1075c8ea8212df065fbb012cc89f9a8fead05c33/pyfaidx/__init__.py#L419)  
and installing (with pip) the packaging library solved the issue (the fasta.bgz read fine)

**Comment by mdshw5** [comment]
Thanks for reporting this. I admit that I didn't understand your issue at first and forgot about it until today. I'll release a new minor version to address this issue.
