### ISSUE TITLE
Benchmark against other comparable tools

### ISSUE THREAD

**Issue by mdshw5** [mdshw5/pyfaidx#45]
- htslib 
- pyfasta 
- fastahack

**Comment by mdshw5** [comment]
Maybe use https://github.com/lobocv/pyperform

**Comment by mdshw5** [comment]
<iframe width="560" height="420" frameborder="0" seamless="seamless" scrolling="no" src="https://plot.ly/~mdshw5/179.embed?width=560&height=420"></iframe>

**Comment by mdshw5** [comment]
![402c000_random_1kb_reads](https://cloud.githubusercontent.com/assets/819554/5895037/30232a48-a4e1-11e4-91b4-6945b5eecade.png)

**Comment by swheelan** [comment]
That was fast -- this is looking very reasonable. 40,000 reads is pretty small though -- is it worth checking how this scales?

**Comment by mdshw5** [comment]
![n_1kb_reads_from_fasta_file](https://cloud.githubusercontent.com/assets/819554/5895244/61368840-a4e7-11e4-8086-59e66926bc05.png)
