### ISSUE TITLE
pyfaidx correctly installed but not working. error: unrecognized arguments

### ISSUE THREAD

**Issue by efr3m** [mdshw5/pyfaidx#46]
I installed pyfaidx as indicated. 
Typing 

    faidx 
    usage: faidx [-h] [-b BED] [--stats] [-c] [-r] [-n] [--split-files] [--lazy]
                 [--default-seq DEFAULT_SEQ] [-d DELIMITER]
                 [--mask-with-default-seq | --mask-by-case] [--version]
                 fasta [regions [regions ...]]
    .....

hower, when I try to run something it always tells me that there is an unrecognized arguments in my comand. The same is true if I use the example files.

    faidx --stats tests/data/genes.fasta
    usage: faidx [-h] [-b BED] [--stats] [-c] [-r] [-n] [--split-files] [--lazy]
                 [--default-seq DEFAULT_SEQ] [-d DELIMITER]
                 [--mask-with-default-seq | --mask-by-case] [--version]
                 fasta [regions [regions ...]]
    faidx: error: unrecognized arguments: tests/data/genes.fasta

I do not understand what I am missing here.

**Comment by mdshw5** [comment]
What version of pyfaidx are you using?

Matt Shirley

**Comment by efr3m** [comment]
0.3.4

**Comment by mdshw5** [comment]
I think you might have cloned the git repository master branch and installed that. If you use `pip install pyfaidx` to install v0.3.4 from PyPI I think you won't have this issue. It looks like I've broken the `faidx` script in the current repository tip.

**Comment by mdshw5** [comment]
Hey @efr3m - thanks for your issue report. I've fixed the issue in the master branch now. If you want to confirm it fixes your issue that would be helpful for me.

**Comment by efr3m** [comment]
Thanks.
I unistalled and reinstalled using `pip install pyfaidx`. Then tested:

`faidx --stats test_cat2 
Ad2	291`

It works.
Thanks again.

**Comment by mdshw5** [comment]
Thanks for checking back in!
