### ISSUE TITLE
Reindex file if time stamp on fasta is newer than on index?

### ISSUE THREAD

**Issue by deannachurch** [mdshw5/pyfaidx#50]
It would be great if the index were automatically recreated if the fasta file has a new time stamp than the .fai file. I just did this test as we had to rebuild a fasta we are using and reindexing did not occur. 

thanks for considering!

**Comment by mdshw5** [comment]
It's a good idea and something I can definitely put in the next release. Thanks for the suggestion!

**Comment by deannachurch** [comment]
Thanks for the quick response! This is great.

**Comment by mdshw5** [comment]
After the new version passes integration tests (in an hour or so), it will be released to PyPI and you should be able to upgrade to it using `pip install --upgrade pyfaidx`. Please let me know if you encounter any issues, or have any other ideas!
