### ISSUE TITLE
Document sequence.start as 1-based to avoid confusion

### ISSUE THREAD

**Issue by mdshw5** [mdshw5/pyfaidx#68]

**Comment by handstad** [comment]
For the record, the current start position is +1 compared to what
is given in a slice. For example:

```python
from pygfaidx import Fasta
f = Fasta("./human_g1k_v37_decoy.fasta")
s = f['1'][100000:100005]
s.start
```
`s.start` returns 100001 (one-based), not 100000 (zero-based).

@mdshw5, any chance that you will make it at least an option to use 0-based coordinates both for slicing and start?

**Comment by mdshw5** [comment]
Hey @handstad can you comment on the updates in f8b8a20 and let me know if this addresses your use case?

**Comment by handstad** [comment]
Yes, this looks very nice! Reasonable that the default behavior is kept as it is, so old users are not surprised. As far as I can see the only thing missing is the functionality that actually transforms the coordinate to zero-based?

**Comment by mdshw5** [comment]
Yes. I will add the functionality and make a new release. Mainly I just wanted an opinion about the API.
