### ISSUE TITLE
Add some tests using hypothesis framework

### ISSUE THREAD

**Issue by mdshw5** [mdshw5/pyfaidx#69]
The hypothesis testing framework seems like a great idea, and adding some more tests for functions that have simple argument types should be easy:

https://github.com/DRMacIver/hypothesis

**Comment by endrebak** [comment]
Neat. Did not know about hypothesis.

Ps. you might want to check out `py.test` for regular unit tests. I find it is far more Pythonic than the others and you get away with writing much less code. http://pytest.org/
