### ISSUE TITLE
Read from bgzip compressed files

### ISSUE THREAD

**Issue by danielecook** [mdshw5/pyfaidx#77]
Not sure why I am getting this error. Any ideas?

```
x = Fasta("WBcel235.fa.gz")

In [5]: x.keys()
Out[5]: ['I', 'II', 'III', 'IV', 'V', 'X', 'NC_001328.1']

x["I"][1:100]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 5: ordinal not in range(128)
```

Keys are read just fine, but not the sequence.

Dan

**Comment by mdshw5** [comment]
Can you point me to the file?

**Comment by danielecook** [comment]
Here is a link: 

http://danielecook.s3.amazonaws.com/WBcel235.fa.gz

**Comment by mdshw5** [comment]
:) I think you'll have better luck if you uncompress the file first.

**Comment by danielecook** [comment]
Interesting! I thought it could read gzipped files because it found the
keys!finds the keys!

**Comment by danielecook** [comment]
Thank you!

**Comment by danielecook** [comment]
Out of curiosity - is there a reason it doesn't? Or couldn't be implemented?

**Comment by mdshw5** [comment]
Hmmm... I am not sure that it could be implemented. It's unexpected that the keys would be found. Actually I can't reproduce that - are you sure that the index wasn't pre-existing?

```python
Python 3.4.3 (default, May  1 2015, 19:14:18) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyfaidx import Fasta
>>> x = Fasta("WBcel235.fa.gz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shirlma2/Library/Python/3.4/lib/python/site-packages/pyfaidx/__init__.py", line 623, in __init__
    sequence_always_upper=sequence_always_upper)
  File "/Users/shirlma2/Library/Python/3.4/lib/python/site-packages/pyfaidx/__init__.py", line 267, in __init__
    self.build_index()
  File "/Users/shirlma2/Library/Python/3.4/lib/python/site-packages/pyfaidx/__init__.py", line 338, in build_index
    for i, line in enumerate(fastafile):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
>>> x.keys()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'x' is not defined
```

**Comment by mdshw5** [comment]
It looks like `samtools faidx` works on gzipped files, so there's no reason I can't implement it.

**Comment by danielecook** [comment]
I'll look into this too and see what is involved. Thanks!
Dan

**Comment by mdshw5** [comment]
Actually it looks like this only works on block gzip compressed files (which your example happens to be): https://github.com/samtools/samtools/issues/237

```shell
gzip -dc WBcel235.fa.gz | gzip -c > recompressed.fa.gz
$ samtools faidx recompressed.fa.gz I
[fai_load] build FASTA index.
Cannot index files compressed with gzip, please use bgzip
[fai_load] fail to open FASTA index.
Could not load fai index of recompressed.fa.gz
```

**Comment by mdshw5** [comment]
So what's involved is writing a compatible implementation of samtools/htslib/bgzf.c in python...

**Comment by mdshw5** [comment]
Can probably add this functionality using https://github.com/biopython/biopython/blob/master/Bio/bgzf.py

- [ ] write indexer to create .gzi index
- [ ] figure out spec of .gzi index
- [ ] write Faidx method to calculate byte offset (virtual offset?) into file
- [ ] import Biopython if available, otherwise warn user of dependency

**Comment by terrycojones** [comment]
I've just been looking into pyfaidx and also the bgzf module of Biopython, trying to decide between the two (pyfaidx looks easier to use but requires my FASTA to be uncompressed). I think to add bgzf support to pyfaidx, the steps are a bit different from those listed above (though I don't know what you mean by a .gzi index). I'd do:

- Indexer looks to see if the FASTA file ends in .bgz if so, it opens it with BgzfFile.open
- The file is read in the normal way, but the `tell` function is used to obtain (virtual) offsets, which are written to the .fai file like any other offset. I think this would just be a matter of removing the manual offset calculation from `Faidx.build_index` and just using `fastafile.tell()`. The `build_index` method would be the thing that looked at the file extension and decided whether to use the builtin `open` or the Bgzf version. It might be worth raising an error on files that don't end in `.fasta` or `.bgz`, so people don't expect to be able to open a regular `.gz` file.
- When opening a file, if the name ends in .bgz, open with Bgzf

I'm not 100% sure the above is right, but I think so. In which case the change wouldn't be much work. Does that sound right? I'm happy to help with the change.

**Comment by terrycojones** [comment]
Just re-read my comment, and it's quite garbled / repetitive - sorry!

**Comment by mdshw5** [comment]
So, @terrycojones - this feature is almost working, but there is a small hitch. When you request a region spanning blocks in a BGZF file, this is a special case:
```
$ faidx tests/data/genes.fasta.gz "gi|530364725|ref|XR_241080.1|:260-270"
>gi|530364725|ref|XR_241080.1|:260-270
CCGCTTTTGAA
```
```
$ faidx tests/data/genes.fasta.gz "gi|530364725|ref|XR_241080.1|:270-280"
Traceback (most recent call last):
  File "pyfaidx/venv3.5/bin/faidx", line 9, in <module>
    load_entry_point('pyfaidx==0.4.8.4', 'console_scripts', 'faidx')()
  File "pyfaidx/venv3.5/lib/python3.5/site-packages/pyfaidx-0.4.8.4-py3.5.egg/pyfaidx/cli.py", line 170, in main
  File "pyfaidx/venv3.5/lib/python3.5/site-packages/pyfaidx-0.4.8.4-py3.5.egg/pyfaidx/cli.py", line 52, in write_sequence
  File "pyfaidx/venv3.5/lib/python3.5/site-packages/pyfaidx-0.4.8.4-py3.5.egg/pyfaidx/cli.py", line 64, in fetch_sequence
  File "pyfaidx/venv3.5/lib/python3.5/site-packages/pyfaidx-0.4.8.4-py3.5.egg/pyfaidx/__init__.py", line 619, in __getitem__
  File "pyfaidx/venv3.5/lib/python3.5/site-packages/pyfaidx-0.4.8.4-py3.5.egg/pyfaidx/__init__.py", line 760, in get_seq
  File "pyfaidx/venv3.5/lib/python3.5/site-packages/pyfaidx-0.4.8.4-py3.5.egg/pyfaidx/__init__.py", line 491, in fetch
  File "pyfaidx/venv3.5/lib/python3.5/site-packages/pyfaidx-0.4.8.4-py3.5.egg/pyfaidx/__init__.py", line 524, in from_file
  File "pyfaidx/venv3.5/lib/python3.5/site-packages/Bio/bgzf.py", line 619, in seek
    % (within_block, len(self._buffer)))
ValueError: Within offset 65281 but block size only 65280
```

I'll have to dig into this a bit more, but most of the tests pass. I think there's just a small issue with how we're using virtual offsets for the seek and read operations when fetching sequence. It's too late for me to think about this anymore, so I'll come back to it in a while.

**Comment by terrycojones** [comment]
Hi. Only just saw this...

I think the solution has to be to use `self.file.seek(i.offset)`, then to `read` the bytes through the end of the wanted region, then to return just the wanted last part of that read (i.e., the wanted region) with the newlines stripped. Does that make sense?

In pseudocode (using some vars that are in the present code):

```python
if self._bgzf:
    self.file.seek(i.offset)
    n = start0 + newlines_before + newlines_inside + seq_len
    data = self.file.read(n).decode()
    return data[start0 + newlines_before].replace('\n', '')
```

I'm not sure about the details of the above, but I'm sure the answer lies in seeking to the already known (valid) offset and reading from there.  I.e., you can't add to an offset in the bgzf file, but you can read forward from that offset.

**Comment by mdshw5** [comment]
Funny, that looks like actual code that will work 😉

**Comment by terrycojones** [comment]
Yes, maybe :-)

BTW, I usually write tests for these kinds of things, but as I guess you know it can be painful to test code that uses `open` multiple times.  Also, your tests touch the filesystem, which I almost never do (people who write large test suites and want them to run very quickly go to great lengths to avoid touching the filesystem, talking to databases, going over the network, etc).

I just added a class to my own code that uses your `Fasta` class. I wrote a test for it that you might like to look at.  It uses the `mock` library to mock `open`, and an `Open` class to return the right thing on all the calls to `open` (your code makes 4 of them when the `.fai` file does not exist).

I also normally mock out things like `os.path.exists` and `os.path.getmtime` to have them return values of my choosing, to test different pathways through the code.  Anyway, the example is at https://github.com/terrycojones/dark-matter/blob/add-fai-support-510/test/test_fasta.py#L453 in case you feel like having a look.

I don't know if this is the "right" way to mock out open and have it return exactly what you want each time it is called, but it's the way I do it. The mock docs (last I checked anyway) aren't really helpful on that subject. So I came up with the approach I use over the years.  It's a lot of work to get tests like this to work...

**Comment by terrycojones** [comment]
Another reason I've been a bit slack here on testing is that I'm not sure to what extent the tests I would write would be supported under Python 2.6.  I stopped using (or supporting) 2.6 a long time ago, and suspect that things like the mock library may not be available, etc.  I don't really know, and I'm not keen to go back to finding out :-)   Does `pyfaidx` have 2.6 users?  It's hard enough to support 2.7 and 3 and pypy.

**Comment by terrycojones** [comment]
One more comment on testing the bgzf stuff. I just wrote my own class to build FASTA indices and store them in an sqlite3 database. After a bit of fiddling I got a proper test working, that constructs bgzf data and mocks out `bgzf.open`. You can see the test at https://github.com/acorg/dark-matter/blob/master/test/test_fasta.py#L1180 in case it's of any use. The class that builds the sqlite database and provides random access to sequences is at https://github.com/acorg/dark-matter/blob/master/dark/fasta.py#L224

**Comment by mdshw5** [comment]
I like the idea of mocking out IO operations, but it seems like right now my test suite is not broken, so I'll wait. I did have a chance to update some tests and added logic to avoid calling any methods that don't work on BGZF files. See #111 for a bit more detail. I'll cut a `v0.4.9` release with the goodies.
