### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by mdshw5** [mdshw5/pyfaidx#78]
Remaining issues related to packaging:

- [ ] test data should be present/downloaded when test suite is run

**Comment by mdshw5** [comment]
Hey @tillea would it be okay for have the test data download when the test suite is run?

**Comment by mdshw5** [comment]
This should be fixed in the current release. I'll wait until tests pass, and then push a point release at v0.4.5.1.

The tests that require the big data will just bee skipped, which I think is an okay compromise.

**Comment by tillea** [comment]
Thanks a lot, uploaded to Debian new queue after successful build

On Mon, Nov 16, 2015 at 05:21:41PM -0800, Matt Shirley wrote:
> This should be fixed in the current release. I'll wait until tests pass, and then push a point release at v0.4.5.1.
> 
> The tests that require the big data will just bee skipped, which I think is an okay compromise.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mdshw5/pyfaidx/issues/78#issuecomment-157229370

-- 
http://fam-tille.de
