### ISSUE TITLE
FastaIndexingError: Line length of fasta file is not consistent! Inconsistent line found in >MT at line 11.

### ISSUE THREAD

**Issue by endrebak** [mdshw5/pyfaidx#83]
In the file http://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz there is a region that looks like this (edited to create minimal example):

```
>MT
CTCCGGGCCCATAACACTTGGGGGTAGCTAAAGTGAACTGTATCCGACATCTGGTTCCTACTTCAGGGTC
ATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATG

>GL000207.1 dna:supercontig supercontig::GL000207.1:1:4262:1
CATACATTTAATATACCCTCACCATACAGAATGTTCTTTCCCTATTACATAAGGAGTATA
```

Because of the empty line, pyfaidx claims that the line length of the fasta is inconsistent:

```
/local/home/endrebak/anaconda/lib/python2.7/site-packages/pyfaidx/__init__.pyc in __init__(self, filename, default_seq, key_function, as_raw, strict_bounds, read_ahead, mutable, split_char, filt_function, one_based_attributes, sequence_always_upper)
    621                            read_ahead=read_ahead, mutable=mutable, split_char=split_char,
    622                            filt_function=filt_function, one_based_attributes=one_based_attributes,
--> 623                            sequence_always_upper=sequence_always_upper)
    624         self.keys = self.faidx.index.keys
    625         if not self.mutable:

/local/home/endrebak/anaconda/lib/python2.7/site-packages/pyfaidx/__init__.pyc in __init__(self, filename, default_seq, key_function, as_raw, strict_bounds, read_ahead, mutable, split_char, filt_function, one_based_attributes, sequence_always_upper)
    268             except FastaIndexingError as e:
    269                 os.remove(self.indexname)
--> 270                 raise FastaIndexingError(e)
    271             self.read_fai(split_char)
    272

FastaIndexingError: Line length of fasta file is not consistent! Inconsistent line found in >MT at line 11.
```

The fasta file above is obviously malformed, but is this something `pyfaidx` can/should handle? I'm guessing many people will experience the same problem due to the file I linked to is so common.

Either way, the error message should lead them to error.

**Comment by endrebak** [comment]
For those coming here wondering how to fix the genome file, merely do:

`sed -i '/^$/d' ~/genomes/human_g1k_v37.fasta`

Will be slooow though.

**Comment by mdshw5** [comment]
If this is something samtools handles then I'm open to changing behavior. 

Matt Shirley

**Comment by endrebak** [comment]
```
samtools 1.2
Using htslib 1.2.1
```

was able to create an index. Whether you want to support such files is up to you.

Other possibilities that do not entail writing as much code would be to 1) create a faq for common fasta errors and how to fix them (and link to it in the error message) and/or 2) print the context of where the error occured +/- 5 lines before after for example (searching in giant files is time consuming)..

**Comment by mdshw5** [comment]
@endrebak I think it's important to allow this case to exist, and so I've refactored the indexing logic and added tests. If you care to test 858d844 on your data, that would be great - I added your minimal example as test data as well.

**Comment by endrebak** [comment]
Works well, thanks!

As an unimportant aside, I wonder if the blank line is there to separate the regular chromosomes from the MT data, contigs and other stuff; there is only one blank line - perhaps put there by intention? (I said the file was obviously malformed previously, now I am not so sure.)
