### ISSUE TITLE
warn on old index

### ISSUE THREAD

**Issue by brentp** [mdshw5/pyfaidx#91]
having apparently stale fai files seems pretty common due to moving stuff around in a shared environment. In cases where the fai has an mtime < the fasta, I think the behaviour should be to warn, not re-build.

**Comment by brentp** [comment]
To add to this, when using the shared fasta file. I can't even use pyfaidx as I dont have permission to overwrite the .fai

**Comment by mdshw5** [comment]
> as I don't have permission to overwrite the .fai
I've had this issue before, and I think your suggestion is appropriate. I'll change the default behavior and add a warning message.

**Comment by mdshw5** [comment]
Hey @brentp I've updated this in master. If you want to wait until tests pass and then give the code a shot, I'd appreciate the help. 

The default behavior now is still to rebuild the old index, but I've (hopefully) added instructions in the resulting exception that point the user to use `Fasta(rebuild=False)` or `Faidx(rebuild=False)` or `$ faidx --no-rebuild`. I haven't tested these yet, but please let me know if this interface would be acceptable for you.

**Comment by mdshw5** [comment]
It looks like my builds are failing because of an [unfortunate regression in pysam](https://github.com/pysam-developers/pysam/issues/246), so feel free to test whenever you have time.

**Comment by mdshw5** [comment]
Looks like this is okay, so I'll mark this issue as closed.
