### ISSUE TITLE
Potential unreleased in Faidx.from_file that can lead to deadlock

### ISSUE THREAD

**Issue by dhauge** [mdshw5/pyfaidx#94]
In 'Faidx.from_file', a 'self.file.seek' call is between the acquisition of the lock and the start of the 'try' block that releases the lock. Thus, if the 'seek' throws an exception, the lock will not be released.

``` python
        self.lock.acquire()
        self.file.seek(bstart)

        try:
            if bstart + seq_blen > i.bend and not self.strict_bounds:
...
```

This may be a somewhat obscure case because 'seek' will rarely fail, but it does when the file is closed. The following test demonstrates a deadlock (it will hang, and never complete)

``` python
class SynchronizationTests(TestCase):
    def test_unreleased_lock(self):
        fasta = Fasta('data/genes.fasta', as_raw=True, strict_bounds=True)
        fasta.close()
        try:
            fasta['gi|557361099|gb|KF435150.1|'][100:100]
        except ValueError:
            pass

        fasta['gi|557361099|gb|KF435150.1|'][100:100]
```

The synchronization could be made both safer and simpler using the 'with self.lock:' construct, as in

``` python
        with self.lock:
            self.file.seek(bstart)
            if bstart + seq_blen > i.bend and not self.strict_bounds:
                seq_blen = i.bend - bstart
            elif bstart + seq_blen > i.bend and self.strict_bounds:
                raise FetchError("Requested end coordinate {0:n} outside of {1}. "
                                 "\n".format(end, rname))
            if seq_blen > 0:
                seq = self.file.read(seq_blen).decode()
            elif seq_blen == 0:
                seq = ''
            elif seq_blen <= 0 and not self.strict_bounds:
                seq = ''
            elif seq_blen <= 0 and self.strict_bounds:
                raise FetchError("Requested coordinates start={0:n} end={1:n} are "
                                 "invalid.\n".format(start, end))
```

The 'with self.lock:' should arguably be used throughout the code instead of explicit 'lock.acquire/lock.relese' pairs. I can create a patch if you'd like that does this.

**Comment by mdshw5** [comment]
I think this is a great idea. Please submit a patch. If for some reason I start working on this I'll update the issue so you don't duplicate efforts!
