### ISSUE TITLE
ValueError: Coordinates start=16572 and end=16571 imply a diffent length than sequence (length 0).

### ISSUE THREAD

**Issue by junjieahaha** [mdshw5/pyfaidx#99]
I am new in  bioinformatics.
Now i am trying to extract sequence from reference genome (hg19.fa,downloaded from UCSC).
Input file is like  :
```
'SN7001388:465:HFKWJBCXX:1:1114:2336:14175      chr1   	14304--14314     
'SN7001388:465:HFKWJBCXX:1:1114:2336:14175      chr1	        14432--14442
'SN7001388:465:HFKWJBCXX:1:1114:2336:14175      chr1	        14547--14557
'SN7001388:465:HFKWJBCXX:1:1114:2336:14175      chr1	         14548--14458
the output file is like:
>'SN7001388:465:HFKWJBCXX:1:1114:2336:14175'	chr1	14306--14316
CTGCTCAGTT
>'SN7001388:485:HFKWJBCXX:1:1114:23517:27506'	chr1	14300--14310
TGGTTTCTGC
>'SN7001388:485:HFKWJBCXX:1:1209:4064:91134'	chr1	14500--14510
TGGTTTCTGC
>'SN7001388:485:HFKWJBCXX:1:2206:4550:23559'	chr1	14386--14396
TAAAAGCACA
```
the code is :
```python
the_sequence = ref_genes[chrom_id][int(start_position):int(end_position)]
It works well,but when it comes to the line of 20000000,
it prints Traceback (most recent call last):
  File "/home/user/python/python_try_to_extract_fast_from_ref_gen.py", line 17, in <module>
    the_sequence = ref_genes[chrom_id][int(start_position):int(end_position)]
  File "/usr/local/lib/python2.7/dist-packages/pyfaidx/__init__.py", line 557, in __getitem__
    return self._fa.get_seq(self.name, start + 1, stop)[::step]
  File "/usr/local/lib/python2.7/dist-packages/pyfaidx/__init__.py", line 117, in __getitem__
    raise ValueError("Coordinates start=%s and end=%s imply a diffent length than sequence (length %s)." % (self.start, self.end, len(self.seq)))
ValueError: Coordinates start=16572 and end=16571 imply a diffent length than sequence (length 0).
```
The lines of input are all the same,i had checked the line ,the start position is obviously not the 16572 ,the end position is also not 16571.I just don't understand how could it break?
Thanks

**Comment by mdshw5** [comment]
Thanks for reporting this. Could I ask you to post the content of line 20000000 and a few lines before? Also, this may be related to issue #93. If so, are you setting `strict_bounds=True`? Maybe try disabling bounds checking and see if you still have a problem.

**Comment by junjieahaha** [comment]
'SN7001388:485:HFKWJBCXX:1:2110:16577:12628' chrM 16530 16540
'SN7001388:485:HFKWJBCXX:2:1104:8575:67359' chrM 16516 16526
'SN7001388:485:HFKWJBCXX:2:1107:17151:18985' chrM 16531 16541
'SN7001388:485:HFKWJBCXX:2:1112:8963:78196' chrM 16513 16523
'SN7001388:485:HFKWJBCXX:1:1107:19582:46423' chrM 16507 16517
'SN7001388:485:HFKWJBCXX:1:1210:18146:82860' chrM 16499 16509
'SN7001388:485:HFKWJBCXX:1:1216:20087:31775' chrM 16506 16516
'SN7001388:485:HFKWJBCXX:1:2108:10930:21408' chrM 16554 16564
'SN7001388:485:HFKWJBCXX:1:2211:2212:28478' chrM 16507 16517
'SN7001388:485:HFKWJBCXX:2:2101:4153:55861' chrM 16506 16516
'SN7001388:485:HFKWJBCXX:2:2112:4740:73177' chrM 16526 16536   #(here)
 'SN7001388:485:HFKWJBCXX:2:2207:17407:49712' chrM 16531 16541
'SN7001388:485:HFKWJBCXX:2:1102:18105:63328' chrM 16553 16563
'SN7001388:485:HFKWJBCXX:2:1108:7836:87565' chrM 16531 16541
'SN7001388:485:HFKWJBCXX:2:2106:6144:55974' chrM 16544 16554
'SN7001388:485:HFKWJBCXX:2:2109:19164:69776' chrM 16530 16540
'SN7001388:485:HFKWJBCXX:2:1204:7295:14403' chrM 16524 16534
'SN7001388:485:HFKWJBCXX:1:1211:3017:45541' chrM 16531 16541
'SN7001388:485:HFKWJBCXX:1:1105:4672:17099' chrM 16554 16564
'SN7001388:485:HFKWJBCXX:2:1213:18805:100476' chrM 16521 16531
'SN7001388:485:HFKWJBCXX:1:2202:6044:24141' chrM 16512 16522


the line is up there.
the code:
import os
from pyfaidx import Fasta
import re
if os.path.isdir('/media/user/seq/'):
    os.chdir('/media/user/seq/')

ref_genes = Fasta('/media/user/ref/hg19.fa')
id_file = open('/media/user/id_position','r')
f_for_write = open('test','w+')
for line in id_file:
    line = line.strip('\n')
    linesplit = line.split()
    seq_id = str(linesplit[0])
    chrom_id =str(linesplit[1]).strip()
    start_position = linesplit[2].strip()
    end_position = linesplit[3].strip()
    the_sequence = ref_genes[chrom_id][int(start_position):int(end_position)]
    
    
    all_text = '>'+seq_id+'	'+str(chrom_id)+'	'+str(start_position)+'--'+str(end_position)+'\n'+str(the_sequence)

I mean that  the format  is the same for all input data.
Thank you.

**Comment by mdshw5** [comment]
One thing that I notice is that the length of `chrM` in the hg19 assembly is exactly 16571:

```
chr1    249250621       6       50      51
chr2    243199373       254235646       50      51
chr3    198022430       502299013       50      51
chr4    191154276       704281898       50      51
chr5    180915260       899259266       50      51
chr6    171115067       1083792838      50      51
chr7    159138663       1258330213      50      51
chr8    146364022       1420651656      50      51
chr9    141213431       1569942965      50      51
chr10   135534747       1713980672      50      51
chr11   135006516       1852226121      50      51
chr12   133851895       1989932775      50      51
chr13   115169878       2126461715      50      51
chr14   107349540       2243934998      50      51
chr15   102531392       2353431536      50      51
chr16   90354753        2458013563      50      51
chr17   81195210        2550175419      50      51
chr18   78077248        2632994541      50      51
chr19   59128983        2712633341      50      51
chr20   63025520        2772944911      50      51
chr21   48129895        2837230949      50      51
chr22   51304566        2886323449      50      51
chrX    155270560       2938654113      50      51
chrY    59373566        3097030091      50      51
chrM    16571   3157591135      50      51
```
I also see that there's an extra space at the beginning of line 20,000,001. Maybe your code is actually requesting a slice outside of the chrM coordinates? Maybe adding some logging where you print the coordinates when you raise the error from the `Fasta` object would help clarify the issue:

```python
    ...
    try:
        the_sequence = ref_genes[chrom_id][int(start_position):int(end_position)]
    except ValueError:
        print([chrom_id, start_position, end_position])

    all_text = '>'+seq_id+' '+str(chrom_id)+'   '+str(start_position)+'--'+str(end_position)+'\n'+str(the_sequence)
```

**Comment by junjieahaha** [comment]
Great.
Thank you for your help.
It is beyond the range of chrM .
['chrM', '16571', '16581']
Thank you again.

**Comment by mdshw5** [comment]
No problem!
